#pragma once
/**
 * TR909 Hand Clap (CP) circuit model.
 *
 * From TR-909 schematic (Hand Clap section):
 *  The clap is generated by bursting a noise signal through a specific
 *  resonant filter and applying a multi-stage envelope that produces
 *  the characteristic "flam" (multiple rapid attacks) followed by a tail.
 *
 *  Key circuit elements:
 *   - Noise source (pink/white noise filtered)
 *   - BPF filter: R=10kΩ, C=6.8nF → fc ≈ 2.3 kHz, Q≈4
 *   - Envelope: 4 fast bursts (≈5 ms each) + 1 tail
 *     Burst timing from 555-timer section: IC7
 *       - Burst period ≈ 5 ms (R_b=10kΩ, C_b=470nF)
 *       - Number of bursts: 3 pre-bursts + 1 main
 *   - DECAY pot (VR1, 500 kΩ) → tail decay time
 *   - τ_burst = R_b × C_b ≈ 4.7 ms per burst
 *
 * Schematic cross-reference: Roland TR-909 Service Notes, page 10.
 */

#pragma once
#include <cmath>
#include <random>

class TR909Clap {
public:
    // Component values from schematic
    static constexpr double R_filt  = 10e3;   // 10 kΩ BPF resistor
    static constexpr double C_filt  = 6.8e-9; // 6.8 nF BPF capacitor
    static constexpr double R_burst = 10e3;   // 10 kΩ burst timer resistor
    static constexpr double C_burst = 470e-9; // 470 nF burst timer cap
    static constexpr double tau_burst = R_burst * C_burst; // ~4.7 ms

    float decay = 0.5f;
    float level = 1.0f;

    void prepare(double sampleRate);
    void trigger(float velocity, bool accent = false);
    float process();

private:
    double fs_    = 44100.0;
    double invFs_ = 1.0 / 44100.0;

    // Bandpass filter state
    double filt_y1_  = 0.0, filt_y2_  = 0.0;
    double filt_x1_  = 0.0, filt_x2_  = 0.0;
    double filt_b0_  = 0.0, filt_b1_  = 0.0, filt_b2_  = 0.0;
    double filt_a1_  = 0.0, filt_a2_  = 0.0;

    // Envelope: 4 bursts + tail
    static constexpr int NUM_BURSTS = 4;
    double burstEnv_[NUM_BURSTS] = {};
    double burstDecay_           = 0.0;
    double burstGap_             = 0.0; // samples between burst onsets
    int    burstCounter_         = 0;   // samples since start
    int    burstSampleOffsets_[NUM_BURSTS] = {};

    // Tail envelope
    double tailEnv_   = 0.0;
    double tailDecay_ = 0.0;

    // Master gate
    bool   active_    = false;
    float  velocity_  = 0.0f;

    float accentGain_ = 1.0f;

    std::mt19937 rng_;
    std::uniform_real_distribution<double> noiseDist_{ -1.0, 1.0 };

    void updateFilter();
};
